In [1]:
import numpy as np

docs = ["Hello world",
        "The sun rises in the east",
        "AI is transforming the world",
        "RNNs can remember previous inputs",
        "Deep learning models need lots of data",
        "This is short",
        "Sometimes less is more",
        "Natural language processing is fun and complex",
        "Train your model carefully",
        "I love learning new things"
]

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
tokenizer.word_index

{'is': 1,
 'the': 2,
 'world': 3,
 'learning': 4,
 'hello': 5,
 'sun': 6,
 'rises': 7,
 'in': 8,
 'east': 9,
 'ai': 10,
 'transforming': 11,
 'rnns': 12,
 'can': 13,
 'remember': 14,
 'previous': 15,
 'inputs': 16,
 'deep': 17,
 'models': 18,
 'need': 19,
 'lots': 20,
 'of': 21,
 'data': 22,
 'this': 23,
 'short': 24,
 'sometimes': 25,
 'less': 26,
 'more': 27,
 'natural': 28,
 'language': 29,
 'processing': 30,
 'fun': 31,
 'and': 32,
 'complex': 33,
 'train': 34,
 'your': 35,
 'model': 36,
 'carefully': 37,
 'i': 38,
 'love': 39,
 'new': 40,
 'things': 41}

In [5]:
# Frequency distribution of words
tokenizer.word_counts

OrderedDict([('hello', 1),
             ('world', 2),
             ('the', 3),
             ('sun', 1),
             ('rises', 1),
             ('in', 1),
             ('east', 1),
             ('ai', 1),
             ('is', 4),
             ('transforming', 1),
             ('rnns', 1),
             ('can', 1),
             ('remember', 1),
             ('previous', 1),
             ('inputs', 1),
             ('deep', 1),
             ('learning', 2),
             ('models', 1),
             ('need', 1),
             ('lots', 1),
             ('of', 1),
             ('data', 1),
             ('this', 1),
             ('short', 1),
             ('sometimes', 1),
             ('less', 1),
             ('more', 1),
             ('natural', 1),
             ('language', 1),
             ('processing', 1),
             ('fun', 1),
             ('and', 1),
             ('complex', 1),
             ('train', 1),
             ('your', 1),
             ('model', 1),
             ('carefully',

In [6]:
len(tokenizer.word_index)

41

In [7]:
# Nos of sentences in the document
tokenizer.document_count

10

In [8]:
# Generate integer encoder sequences
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[5, 3],
 [2, 6, 7, 8, 2, 9],
 [10, 1, 11, 2, 3],
 [12, 13, 14, 15, 16],
 [17, 4, 18, 19, 20, 21, 22],
 [23, 1, 24],
 [25, 26, 1, 27],
 [28, 29, 30, 1, 31, 32, 33],
 [34, 35, 36, 37],
 [38, 39, 4, 40, 41]]

In [9]:
from tensorflow.keras.utils import pad_sequences

In [10]:
# Padding the sequences to create matrix
sequences = pad_sequences(sequences, padding = 'post')


In [11]:
sequences

array([[ 5,  3,  0,  0,  0,  0,  0],
       [ 2,  6,  7,  8,  2,  9,  0],
       [10,  1, 11,  2,  3,  0,  0],
       [12, 13, 14, 15, 16,  0,  0],
       [17,  4, 18, 19, 20, 21, 22],
       [23,  1, 24,  0,  0,  0,  0],
       [25, 26,  1, 27,  0,  0,  0],
       [28, 29, 30,  1, 31, 32, 33],
       [34, 35, 36, 37,  0,  0,  0],
       [38, 39,  4, 40, 41,  0,  0]], dtype=int32)

In [12]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten, SimpleRNN

In [18]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten, SimpleRNN

model = Sequential()
model.add(Embedding(input_dim=42, output_dim=2))  # 42 x 2 | Dynamically it will assign values, at run time.

model.summary()


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer = 'adam', metrics=['accuracy'])

In [24]:
tokenizer.word_index

{'is': 1,
 'the': 2,
 'world': 3,
 'learning': 4,
 'hello': 5,
 'sun': 6,
 'rises': 7,
 'in': 8,
 'east': 9,
 'ai': 10,
 'transforming': 11,
 'rnns': 12,
 'can': 13,
 'remember': 14,
 'previous': 15,
 'inputs': 16,
 'deep': 17,
 'models': 18,
 'need': 19,
 'lots': 20,
 'of': 21,
 'data': 22,
 'this': 23,
 'short': 24,
 'sometimes': 25,
 'less': 26,
 'more': 27,
 'natural': 28,
 'language': 29,
 'processing': 30,
 'fun': 31,
 'and': 32,
 'complex': 33,
 'train': 34,
 'your': 35,
 'model': 36,
 'carefully': 37,
 'i': 38,
 'love': 39,
 'new': 40,
 'things': 41}

In [19]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
[[[ 4.0089753e-02 -2.8899089e-03]
  [-1.7991029e-02 -4.6075094e-02]
  [ 1.9905679e-03 -3.9503135e-02]
  [ 1.9905679e-03 -3.9503135e-02]
  [ 1.9905679e-03 -3.9503135e-02]
  [ 1.9905679e-03 -3.9503135e-02]
  [ 1.9905679e-03 -3.9503135e-02]]

 [[-4.3799654e-03  3.6439452e-02]
  [ 6.6610947e-03  1.8307332e-02]
  [ 3.4773897e-02 -4.0760349e-02]
  [ 1.9711424e-02 -1.1650123e-02]
  [-4.3799654e-03  3.6439452e-02]
  [-3.7502147e-02 -4.4282246e-02]
  [ 1.9905679e-03 -3.9503135e-02]]

 [[-5.5479892e-03 -1.2880970e-02]
  [ 3.2972779e-02 -2.2663951e-02]
  [ 9.2032664e-03 -1.8297829e-02]
  [-4.3799654e-03  3.6439452e-02]
  [-1.7991029e-02 -4.6075094e-02]
  [ 1.9905679e-03 -3.9503135e-02]
  [ 1.9905679e-03 -3.9503135e-02]]

 [[ 1.2170397e-02  9.1099739e-03]
  [-4.1835677e-02  6.6809542e-03]
  [ 4.8210446e-02 -4.7867168e-02]
  [-2.6270771e-02  2.2790994e-02]
  [ 2.5689911e-02  2.1836761e-02]
  [ 1.9905679e-03 -3.9503135e-02]
  [ 1.9905679e-03 -3.9503135e-02]]

 

In [25]:
## Full fledged implementation
from tensorflow.keras.datasets import imdb
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten, SimpleRNN

In [26]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [27]:
X_train.shape

(25000,)

In [28]:
X_test.shape

(25000,)

In [29]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [31]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [32]:
X_train.shape

(25000, 50)

In [39]:
# Let's build a simple RNN model
model = Sequential()

model.add(Embedding(input_dim=10000, input_length = X_train[1], output_dim=2))
model.add(SimpleRNN(32, return_sequences=False))    # If True, then hidden state/output of each step is also sent as the main output; here only at the end
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [47]:
np.max(X_train)

np.int32(88585)